apiVersion: v1
kind: Pod
metadata:
   name: gs-spring-boot-pod
   labels:
      componentName: gs-rest-controller
spec:
   containers:
      - name: gs-spring-boot
        image: santanubasu99acr.azurecr.io/gs-spring-boot:v1
        ports:
           - containerPort: 8080