apiVersion: v1
kind: Service
metadata:
   name: gs-spring-boot-loadbalancer
spec:
   type: LoadBalancer
   selector:
      componentName: gs-rest-controller
   ports:
      - port: 80
        targetPort: 8080